"""Typ-Stub fuer das Paket ``MetaTrader5`` (Programm NEUAUFBAU, Auftrag 1, T6 "T").

Warum es diese Datei gibt: ``MetaTrader5`` liegt nur auf Windows-Rechnern mit
Terminal und traegt keine Typinformation. Auf einem Rechner ohne das Paket (die
Linux-CI, ein frischer Klon) meldete ``mypy --strict`` in ``tools/live_betrieb.py``
``import-not-found`` -- und der dort stehende ``type: ignore[import-untyped]`` deckte
genau diesen Fehlercode nicht (Beleg: ``belege/03-nachstellung/03-mypy-linuxfall.txt``).
Mit diesem Stub (``mypy_path = "stubs"`` in ``pyproject.toml``) loest der Import auf
beiden Rechnern gleich auf, und der ``type: ignore`` entfaellt.

Umfang: die Namen, die ``mt5_trading_ai/`` und ``tools/`` benutzen (ermittelt per
grep ueber ``mt5.<name>``/``self._mt5.<name>``/``getattr(mt5, "<NAME>")``), plus die
Felder der Rueckgabestrukturen, die der Adapter liest. Die Strukturen sind im echten
Paket benannte Tupel; hier stehen sie als Klassen mit Nur-Lese-Attributen, weil der
Adapter ausschliesslich Attribute liest. Werte der Konstanten werden nicht behauptet
(``Final[int]``): der Adapter liest sie zur Laufzeit aus dem echten Paket.

Kein Aufruf hierin startet ein Terminal -- es ist eine reine Typbeschreibung.
"""

from datetime import datetime
from typing import Any, Final

# --- Konstanten: Auftragsarten ------------------------------------------------
TRADE_ACTION_DEAL: Final[int]
TRADE_ACTION_PENDING: Final[int]
TRADE_ACTION_SLTP: Final[int]
TRADE_ACTION_MODIFY: Final[int]
TRADE_ACTION_REMOVE: Final[int]
TRADE_ACTION_CLOSE_BY: Final[int]

ORDER_TYPE_BUY: Final[int]
ORDER_TYPE_SELL: Final[int]
ORDER_TYPE_BUY_LIMIT: Final[int]
ORDER_TYPE_SELL_LIMIT: Final[int]
ORDER_TYPE_BUY_STOP: Final[int]
ORDER_TYPE_SELL_STOP: Final[int]
ORDER_TYPE_BUY_STOP_LIMIT: Final[int]
ORDER_TYPE_SELL_STOP_LIMIT: Final[int]
ORDER_TYPE_CLOSE_BY: Final[int]

ORDER_TIME_GTC: Final[int]
ORDER_TIME_DAY: Final[int]
ORDER_TIME_SPECIFIED: Final[int]
ORDER_TIME_SPECIFIED_DAY: Final[int]

ORDER_FILLING_FOK: Final[int]
ORDER_FILLING_IOC: Final[int]
ORDER_FILLING_RETURN: Final[int]

ORDER_STATE_STARTED: Final[int]
ORDER_STATE_PLACED: Final[int]
ORDER_STATE_CANCELED: Final[int]
ORDER_STATE_PARTIAL: Final[int]
ORDER_STATE_FILLED: Final[int]
ORDER_STATE_REJECTED: Final[int]
ORDER_STATE_EXPIRED: Final[int]

POSITION_TYPE_BUY: Final[int]
POSITION_TYPE_SELL: Final[int]

ACCOUNT_TRADE_MODE_DEMO: Final[int]
ACCOUNT_TRADE_MODE_CONTEST: Final[int]
ACCOUNT_TRADE_MODE_REAL: Final[int]

# --- Konstanten: Rueckgabecodes von order_send ------------------------------
TRADE_RETCODE_REQUOTE: Final[int]
TRADE_RETCODE_REJECT: Final[int]
TRADE_RETCODE_CANCEL: Final[int]
TRADE_RETCODE_PLACED: Final[int]
TRADE_RETCODE_DONE: Final[int]
TRADE_RETCODE_DONE_PARTIAL: Final[int]
TRADE_RETCODE_ERROR: Final[int]
TRADE_RETCODE_TIMEOUT: Final[int]
TRADE_RETCODE_INVALID: Final[int]
TRADE_RETCODE_INVALID_VOLUME: Final[int]
TRADE_RETCODE_INVALID_PRICE: Final[int]
TRADE_RETCODE_INVALID_STOPS: Final[int]
TRADE_RETCODE_TRADE_DISABLED: Final[int]
TRADE_RETCODE_MARKET_CLOSED: Final[int]
TRADE_RETCODE_NO_MONEY: Final[int]
TRADE_RETCODE_PRICE_CHANGED: Final[int]
TRADE_RETCODE_PRICE_OFF: Final[int]
TRADE_RETCODE_INVALID_EXPIRATION: Final[int]
TRADE_RETCODE_ORDER_CHANGED: Final[int]
TRADE_RETCODE_TOO_MANY_REQUESTS: Final[int]
TRADE_RETCODE_NO_CHANGES: Final[int]
TRADE_RETCODE_SERVER_DISABLES_AT: Final[int]
TRADE_RETCODE_CLIENT_DISABLES_AT: Final[int]
TRADE_RETCODE_LOCKED: Final[int]
TRADE_RETCODE_FROZEN: Final[int]
TRADE_RETCODE_INVALID_FILL: Final[int]
TRADE_RETCODE_CONNECTION: Final[int]
TRADE_RETCODE_ONLY_REAL: Final[int]
TRADE_RETCODE_LIMIT_ORDERS: Final[int]
TRADE_RETCODE_LIMIT_VOLUME: Final[int]
TRADE_RETCODE_INVALID_ORDER: Final[int]
TRADE_RETCODE_POSITION_CLOSED: Final[int]

# --- Konstanten: Zeitebenen (Adapter: getattr(mt5, f"TIMEFRAME_{wert}")) ----
TIMEFRAME_M1: Final[int]
TIMEFRAME_M2: Final[int]
TIMEFRAME_M3: Final[int]
TIMEFRAME_M4: Final[int]
TIMEFRAME_M5: Final[int]
TIMEFRAME_M6: Final[int]
TIMEFRAME_M10: Final[int]
TIMEFRAME_M12: Final[int]
TIMEFRAME_M15: Final[int]
TIMEFRAME_M20: Final[int]
TIMEFRAME_M30: Final[int]
TIMEFRAME_H1: Final[int]
TIMEFRAME_H2: Final[int]
TIMEFRAME_H3: Final[int]
TIMEFRAME_H4: Final[int]
TIMEFRAME_H6: Final[int]
TIMEFRAME_H8: Final[int]
TIMEFRAME_H12: Final[int]
TIMEFRAME_D1: Final[int]
TIMEFRAME_W1: Final[int]
TIMEFRAME_MN1: Final[int]

# --- Konstanten: Fehlercodes von last_error ---------------------------------
RES_S_OK: Final[int]
RES_E_FAIL: Final[int]
RES_E_INVALID_PARAMS: Final[int]
RES_E_NO_MEMORY: Final[int]
RES_E_NOT_FOUND: Final[int]
RES_E_INVALID_VERSION: Final[int]
RES_E_AUTH_FAILED: Final[int]
RES_E_UNSUPPORTED: Final[int]
RES_E_AUTO_TRADING_DISABLED: Final[int]
RES_E_INTERNAL_FAIL: Final[int]

# --- Rueckgabestrukturen (im echten Paket benannte Tupel) --------------------
class TerminalInfo:
    @property
    def community_account(self) -> bool: ...
    @property
    def community_connection(self) -> bool: ...
    @property
    def connected(self) -> bool: ...
    @property
    def dlls_allowed(self) -> bool: ...
    @property
    def trade_allowed(self) -> bool: ...
    @property
    def tradeapi_disabled(self) -> bool: ...
    @property
    def email_enabled(self) -> bool: ...
    @property
    def ftp_enabled(self) -> bool: ...
    @property
    def notifications_enabled(self) -> bool: ...
    @property
    def mqid(self) -> bool: ...
    @property
    def build(self) -> int: ...
    @property
    def maxbars(self) -> int: ...
    @property
    def codepage(self) -> int: ...
    @property
    def ping_last(self) -> int: ...
    @property
    def community_balance(self) -> float: ...
    @property
    def retransmission(self) -> float: ...
    @property
    def company(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def language(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def data_path(self) -> str: ...
    @property
    def commondata_path(self) -> str: ...
    def _asdict(self) -> dict[str, Any]: ...

class AccountInfo:
    @property
    def login(self) -> int: ...
    @property
    def trade_mode(self) -> int: ...
    @property
    def leverage(self) -> int: ...
    @property
    def limit_orders(self) -> int: ...
    @property
    def margin_so_mode(self) -> int: ...
    @property
    def trade_allowed(self) -> bool: ...
    @property
    def trade_expert(self) -> bool: ...
    @property
    def margin_mode(self) -> int: ...
    @property
    def currency_digits(self) -> int: ...
    @property
    def fifo_close(self) -> bool: ...
    @property
    def balance(self) -> float: ...
    @property
    def credit(self) -> float: ...
    @property
    def profit(self) -> float: ...
    @property
    def equity(self) -> float: ...
    @property
    def margin(self) -> float: ...
    @property
    def margin_free(self) -> float: ...
    @property
    def margin_level(self) -> float: ...
    @property
    def margin_so_call(self) -> float: ...
    @property
    def margin_so_so(self) -> float: ...
    @property
    def margin_initial(self) -> float: ...
    @property
    def margin_maintenance(self) -> float: ...
    @property
    def assets(self) -> float: ...
    @property
    def liabilities(self) -> float: ...
    @property
    def commission_blocked(self) -> float: ...
    @property
    def name(self) -> str: ...
    @property
    def server(self) -> str: ...
    @property
    def currency(self) -> str: ...
    @property
    def company(self) -> str: ...
    def _asdict(self) -> dict[str, Any]: ...

class SymbolInfo:
    @property
    def custom(self) -> bool: ...
    @property
    def chart_mode(self) -> int: ...
    @property
    def select(self) -> bool: ...
    @property
    def visible(self) -> bool: ...
    @property
    def session_deals(self) -> int: ...
    @property
    def session_buy_orders(self) -> int: ...
    @property
    def session_sell_orders(self) -> int: ...
    @property
    def volume(self) -> int: ...
    @property
    def volumehigh(self) -> int: ...
    @property
    def volumelow(self) -> int: ...
    @property
    def time(self) -> int: ...
    @property
    def digits(self) -> int: ...
    @property
    def spread(self) -> int: ...
    @property
    def spread_float(self) -> bool: ...
    @property
    def ticks_bookdepth(self) -> int: ...
    @property
    def trade_calc_mode(self) -> int: ...
    @property
    def trade_mode(self) -> int: ...
    @property
    def start_time(self) -> int: ...
    @property
    def expiration_time(self) -> int: ...
    @property
    def trade_stops_level(self) -> int: ...
    @property
    def trade_freeze_level(self) -> int: ...
    @property
    def trade_exemode(self) -> int: ...
    @property
    def swap_mode(self) -> int: ...
    @property
    def swap_rollover3days(self) -> int: ...
    @property
    def margin_hedged_use_leg(self) -> bool: ...
    @property
    def expiration_mode(self) -> int: ...
    @property
    def filling_mode(self) -> int: ...
    @property
    def order_mode(self) -> int: ...
    @property
    def order_gtc_mode(self) -> int: ...
    @property
    def option_mode(self) -> int: ...
    @property
    def option_right(self) -> int: ...
    @property
    def bid(self) -> float: ...
    @property
    def bidhigh(self) -> float: ...
    @property
    def bidlow(self) -> float: ...
    @property
    def ask(self) -> float: ...
    @property
    def askhigh(self) -> float: ...
    @property
    def asklow(self) -> float: ...
    @property
    def last(self) -> float: ...
    @property
    def lasthigh(self) -> float: ...
    @property
    def lastlow(self) -> float: ...
    @property
    def volume_real(self) -> float: ...
    @property
    def volumehigh_real(self) -> float: ...
    @property
    def volumelow_real(self) -> float: ...
    @property
    def option_strike(self) -> float: ...
    @property
    def point(self) -> float: ...
    @property
    def trade_tick_value(self) -> float: ...
    @property
    def trade_tick_value_profit(self) -> float: ...
    @property
    def trade_tick_value_loss(self) -> float: ...
    @property
    def trade_tick_size(self) -> float: ...
    @property
    def trade_contract_size(self) -> float: ...
    @property
    def trade_accrued_interest(self) -> float: ...
    @property
    def trade_face_value(self) -> float: ...
    @property
    def trade_liquidity_rate(self) -> float: ...
    @property
    def volume_min(self) -> float: ...
    @property
    def volume_max(self) -> float: ...
    @property
    def volume_step(self) -> float: ...
    @property
    def volume_limit(self) -> float: ...
    @property
    def swap_long(self) -> float: ...
    @property
    def swap_short(self) -> float: ...
    @property
    def margin_initial(self) -> float: ...
    @property
    def margin_maintenance(self) -> float: ...
    @property
    def session_volume(self) -> float: ...
    @property
    def session_turnover(self) -> float: ...
    @property
    def session_interest(self) -> float: ...
    @property
    def session_buy_orders_volume(self) -> float: ...
    @property
    def session_sell_orders_volume(self) -> float: ...
    @property
    def session_open(self) -> float: ...
    @property
    def session_close(self) -> float: ...
    @property
    def session_aw(self) -> float: ...
    @property
    def session_price_settlement(self) -> float: ...
    @property
    def session_price_limit_min(self) -> float: ...
    @property
    def session_price_limit_max(self) -> float: ...
    @property
    def margin_hedged(self) -> float: ...
    @property
    def price_change(self) -> float: ...
    @property
    def price_volatility(self) -> float: ...
    @property
    def price_theoretical(self) -> float: ...
    @property
    def price_greeks_delta(self) -> float: ...
    @property
    def price_greeks_theta(self) -> float: ...
    @property
    def price_greeks_gamma(self) -> float: ...
    @property
    def price_greeks_vega(self) -> float: ...
    @property
    def price_greeks_rho(self) -> float: ...
    @property
    def price_greeks_omega(self) -> float: ...
    @property
    def price_sensitivity(self) -> float: ...
    @property
    def basis(self) -> str: ...
    @property
    def category(self) -> str: ...
    @property
    def currency_base(self) -> str: ...
    @property
    def currency_profit(self) -> str: ...
    @property
    def currency_margin(self) -> str: ...
    @property
    def bank(self) -> str: ...
    @property
    def description(self) -> str: ...
    @property
    def exchange(self) -> str: ...
    @property
    def formula(self) -> str: ...
    @property
    def isin(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def page(self) -> str: ...
    @property
    def path(self) -> str: ...
    def _asdict(self) -> dict[str, Any]: ...

class Tick:
    @property
    def time(self) -> int: ...
    @property
    def bid(self) -> float: ...
    @property
    def ask(self) -> float: ...
    @property
    def last(self) -> float: ...
    @property
    def volume(self) -> int: ...
    @property
    def time_msc(self) -> int: ...
    @property
    def flags(self) -> int: ...
    @property
    def volume_real(self) -> float: ...
    def _asdict(self) -> dict[str, Any]: ...

class TradePosition:
    @property
    def ticket(self) -> int: ...
    @property
    def time(self) -> int: ...
    @property
    def time_msc(self) -> int: ...
    @property
    def time_update(self) -> int: ...
    @property
    def time_update_msc(self) -> int: ...
    @property
    def type(self) -> int: ...
    @property
    def magic(self) -> int: ...
    @property
    def identifier(self) -> int: ...
    @property
    def reason(self) -> int: ...
    @property
    def volume(self) -> float: ...
    @property
    def price_open(self) -> float: ...
    @property
    def sl(self) -> float: ...
    @property
    def tp(self) -> float: ...
    @property
    def price_current(self) -> float: ...
    @property
    def swap(self) -> float: ...
    @property
    def profit(self) -> float: ...
    @property
    def symbol(self) -> str: ...
    @property
    def comment(self) -> str: ...
    @property
    def external_id(self) -> str: ...
    def _asdict(self) -> dict[str, Any]: ...

class TradeOrder:
    @property
    def ticket(self) -> int: ...
    @property
    def time_setup(self) -> int: ...
    @property
    def time_setup_msc(self) -> int: ...
    @property
    def time_done(self) -> int: ...
    @property
    def time_done_msc(self) -> int: ...
    @property
    def time_expiration(self) -> int: ...
    @property
    def type(self) -> int: ...
    @property
    def type_time(self) -> int: ...
    @property
    def type_filling(self) -> int: ...
    @property
    def state(self) -> int: ...
    @property
    def magic(self) -> int: ...
    @property
    def position_id(self) -> int: ...
    @property
    def position_by_id(self) -> int: ...
    @property
    def reason(self) -> int: ...
    @property
    def volume_initial(self) -> float: ...
    @property
    def volume_current(self) -> float: ...
    @property
    def price_open(self) -> float: ...
    @property
    def sl(self) -> float: ...
    @property
    def tp(self) -> float: ...
    @property
    def price_current(self) -> float: ...
    @property
    def price_stoplimit(self) -> float: ...
    @property
    def symbol(self) -> str: ...
    @property
    def comment(self) -> str: ...
    @property
    def external_id(self) -> str: ...
    def _asdict(self) -> dict[str, Any]: ...

class TradeRequest:
    @property
    def action(self) -> int: ...
    @property
    def magic(self) -> int: ...
    @property
    def order(self) -> int: ...
    @property
    def symbol(self) -> str: ...
    @property
    def volume(self) -> float: ...
    @property
    def price(self) -> float: ...
    @property
    def stoplimit(self) -> float: ...
    @property
    def sl(self) -> float: ...
    @property
    def tp(self) -> float: ...
    @property
    def deviation(self) -> int: ...
    @property
    def type(self) -> int: ...
    @property
    def type_filling(self) -> int: ...
    @property
    def type_time(self) -> int: ...
    @property
    def expiration(self) -> int: ...
    @property
    def comment(self) -> str: ...
    @property
    def position(self) -> int: ...
    @property
    def position_by(self) -> int: ...
    def _asdict(self) -> dict[str, Any]: ...

class OrderSendResult:
    @property
    def retcode(self) -> int: ...
    @property
    def deal(self) -> int: ...
    @property
    def order(self) -> int: ...
    @property
    def volume(self) -> float: ...
    @property
    def price(self) -> float: ...
    @property
    def bid(self) -> float: ...
    @property
    def ask(self) -> float: ...
    @property
    def comment(self) -> str: ...
    @property
    def request_id(self) -> int: ...
    @property
    def retcode_external(self) -> int: ...
    @property
    def request(self) -> TradeRequest: ...
    def _asdict(self) -> dict[str, Any]: ...

class OrderCheckResult:
    @property
    def retcode(self) -> int: ...
    @property
    def balance(self) -> float: ...
    @property
    def equity(self) -> float: ...
    @property
    def profit(self) -> float: ...
    @property
    def margin(self) -> float: ...
    @property
    def margin_free(self) -> float: ...
    @property
    def margin_level(self) -> float: ...
    @property
    def comment(self) -> str: ...
    @property
    def request(self) -> TradeRequest: ...
    def _asdict(self) -> dict[str, Any]: ...

# --- Sitzung -----------------------------------------------------------------
# ``initialize`` startet unter Windows das Terminal -- in Tests nie aufrufen.
def initialize(
    path: str = ...,
    *,
    login: int = ...,
    password: str = ...,
    server: str = ...,
    timeout: int = ...,
    portable: bool = ...,
) -> bool: ...
def login(
    login: int, *, password: str = ..., server: str = ..., timeout: int = ...
) -> bool: ...
def shutdown() -> None: ...
def version() -> tuple[int, int, str] | None: ...
def last_error() -> tuple[int, str]: ...

# --- Lesen -------------------------------------------------------------------
def terminal_info() -> TerminalInfo | None: ...
def account_info() -> AccountInfo | None: ...
def symbols_total() -> int: ...
def symbols_get(group: str = ...) -> tuple[SymbolInfo, ...] | None: ...
def symbol_info(symbol: str) -> SymbolInfo | None: ...
def symbol_info_tick(symbol: str) -> Tick | None: ...
def symbol_select(symbol: str, enable: bool = ...) -> bool: ...

# Die Kerzen kommen als strukturiertes numpy-Feld (Spalten time, open, high, low,
# close, tick_volume, spread, real_volume). numpy ist keine Abhaengigkeit dieses
# Pakets (requirements-dev.txt), darum hier kein numpy-Typ.
def copy_rates_from(
    symbol: str, timeframe: int, date_from: datetime | int, count: int
) -> Any: ...
def copy_rates_from_pos(
    symbol: str, timeframe: int, start_pos: int, count: int
) -> Any: ...
def copy_rates_range(
    symbol: str, timeframe: int, date_from: datetime | int, date_to: datetime | int
) -> Any: ...
def copy_ticks_from(
    symbol: str, date_from: datetime | int, count: int, flags: int
) -> Any: ...
def copy_ticks_range(
    symbol: str, date_from: datetime | int, date_to: datetime | int, flags: int
) -> Any: ...

# --- Bestaende -----------------------------------------------------------------
# ``None`` heisst hier stets: Abfrage FEHLGESCHLAGEN -- nicht "nichts gefunden".
def positions_total() -> int: ...
def positions_get(
    *, symbol: str = ..., group: str = ..., ticket: int = ...
) -> tuple[TradePosition, ...] | None: ...
def orders_total() -> int: ...
def orders_get(
    *, symbol: str = ..., group: str = ..., ticket: int = ...
) -> tuple[TradeOrder, ...] | None: ...
def history_orders_total(date_from: datetime | int, date_to: datetime | int) -> int: ...
def history_orders_get(
    date_from: datetime | int = ...,
    date_to: datetime | int = ...,
    *,
    group: str = ...,
    ticket: int = ...,
    position: int = ...,
) -> tuple[TradeOrder, ...] | None: ...

# --- Schreiben (nur ueber Mt5Venue.submit_order, nie direkt) -----------------
def order_calc_margin(
    action: int, symbol: str, volume: float, price: float
) -> float | None: ...
def order_calc_profit(
    action: int, symbol: str, volume: float, price_open: float, price_close: float
) -> float | None: ...
def order_check(request: dict[str, Any]) -> OrderCheckResult | None: ...
def order_send(request: dict[str, Any]) -> OrderSendResult | None: ...
